spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/certificate?useSSL=true&serverTimezone=UTC
    username: postgres
    password: Osamu_720290
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

#pagination:
#  default:
#    pageSize: 10
#    pageNumber: 0