spring:
  #  jpa:
  #    hibernate:
  #      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/certificate?useSSL=true&serverTimezone=UTC
    username: postgres
    password: Osamu_720290
    driver-class-name: org.postgresql.Driver

#pagination:
#  default:
#    pageSize: 10
#    pageNumber: 0
