spring:
  datasource:
      orders:
        url: jdbc:postgresql://localhost:5432/node${PORT}
        username: postgres
        password: Osamu_720290
        driverClassName: org.postgresql.Driver
      commitlog:
        url: jdbc:postgresql://localhost:5432/commit_log
        username: postgres
        password: Osamu_720290
        driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      platform: postgresql
      mode: always

server:
  port: ${PORT}
  sourcesPort: 8070, 8080, 8090
  replicas:
    8070: 8071, 8072
    8080: 8081, 8082
    8090: 8091, 8092
  cluster:
    8070: 8070, 8071, 8072
    8080: 8080, 8081, 8082
    8090: 8090, 8091, 8092

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

