spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/node${PORT:8080}
    username: postgres
    password: Osamu_720290
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}


cluster:
  '{ "node8080":8080, 
     "node8081":8081,
     "node8082":8082
   }'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
